name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Game SVG
        uses: Platane/snk@v3
        with:
          github_user_name: amritha-pradeep99
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist
